### ISSUE TITLE
Babelify 7 incompatability

### ISSUE THREAD

**Issue by jamesvillarrubia** [vuejs-templates/browserify#1] opened 2016-01-26 16:12 UTC
I've used this, but I've had to downgrade babelify to 6.4 in order to get it to work.  Here's the error message:

import Vue from 'vue';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by yyx990803** [comment] 2016-01-26 18:32
Can't reproduce...

**Comment by chrisvfritz** [comment] 2016-03-19 17:20
Closing for now, but happy to reopen if someone is able to reproduce and provide more information about their environment.

**Closed by chrisvfritz** 2016-03-19 17:20 UTC

**Comment by gambolputty** [comment] 2017-04-04 12:53
I'm getting the same error after importing Vuex:

```
C:\Users\Gregor\Dropbox\Server\wp-content\themes\labourgames-js\node_modules\vuex\src\plugins\logger.js:3
import { deepCopy } from '../util'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

.babelrc:
```
{
  "presets": ["es2015", "stage-2"],
}
```

.eslintrc:
```
{
  "extends": "standard",
  "plugins": [
    "html"
  ],
  "env": {},
  globals: {
      "wp": true
  }
}
```

package.json:
```
{
  "name": "labourgames-js",
  "version": "0.1.0",
  "description": "A Vue.js project",
  "author": "gambolputty <gregorweichbrodt@gmail.com>",
  "private": true,
  "scripts": {
    "watchify": "watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js",
    "serve": "http-server -c 1 -a localhost",
    "dev": "npm-run-all --parallel watchify",
    "lint": "eslint --ext .js,.vue src",
    "build": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/build.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/build.js"
  },
  "browserify": {
    "transform": [
      "babelify",
      "vueify"
    ]
  },
  "browser": {
    "vue": "vue/dist/vue.common.js"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "imagesloaded": "^4.1.1",
    "masonry-layout": "^4.1.1",
    "nprogress": "^0.2.0",
    "vue": "^2.0.1",
    "vue-router": "^2.3.1",
    "vuex": "^2.2.1"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-runtime": "^6.0.0",
    "babelify": "^7.2.0",
    "browserify": "^13.1.0",
    "browserify-hmr": "^0.3.1",
    "cross-env": "^2.0.0",
    "envify": "^3.4.1",
    "eslint": "^3.3.0",
    "eslint-config-standard": "^5.3.5",
    "eslint-plugin-html": "^1.5.2",
    "eslint-plugin-promise": "^2.0.1",
    "eslint-plugin-standard": "^2.0.0",
    "http-server": "^0.9.0",
    "node-sass": "^4.5.2",
    "npm-run-all": "^2.3.0",
    "proxyquireify": "^3.0.1",
    "uglify-js": "^2.5.0",
    "vueify": "^9.0.0",
    "watchify": "^3.4.0"
  }
}
```
